# Generated by Django 3.0.7 on 2020-08-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible'), ('visited', 'Visited')], default='visible', max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('parentPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.QuestPoint')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Quest')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.User'),
        ),
    ]
